project:
  type: website
  output-dir: docs
  
  
website:
  title: "Chris Mantegna"
  navbar:
      left:
      - href: index.qmd
        text: Home
      - projects.qmd
  
  # tools:
   #   - icon: twitter
   #     href: https://twitter.com/SaffireSeahorse
   #   - icon: github
   #    href: https://github.com/ChrisMantegna/mantegna


format:
  html:
    theme: lux
    toc: true

editor: source

