project:
  type: website
  output-dir: docs
  
website:
  title: "Chris Mantegna"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/SaffireSeahorse
      - icon: github
        href: https://github.com/ChrisMantegna/mantegna
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Chris Mantegna"

format:
  html:
    theme: pulse
    toc: true

editor: source

